use_frameworks!

platform :ios, '10.0'

target 'ZcqIAPVender_Example' do
  pod 'ZcqIAPVender', :path => '../'

  target 'ZcqIAPVender_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
